[[plugins]]
repo = 'haya14busa/dein-command.vim'
on_cmd = 'Dein'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertEnter'
hook_add = '''
  let g:deoplete#enable_at_startup = 1
  inoremap <expr><Tab> pumvisible() ? "\<DOWN>" : "\<Tab>"
  inoremap <expr><S-Tab> pumvisible() ? "\<UP>" : "\<S-Tab>"
'''

# temporary comment out
[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
build = 'bash install.sh'
rev = 'next'
hook_add = '''
  set hidden
  let g:LanguageClient_serverCommands = {
    \ 'go': ['gopls'],
    \ 'ruby': [expand('$RBENV_ROOT' . '/versions/2.6.3/bin/solargraph'), 'stdio'],
    \ 'javascript': ['javascript-typescript-stdio']
    \ }
  let g:LanguageClient_loadSettings = 1
  nnoremap <silent> K :call LanguageClient#textDocument_hover()<CR>
  nnoremap <silent> gd :call LanguageClient#textDocument_definition()<CR>
'''

# use coc.nvim
# [[plugins]]
# repo = 'neoclide/coc.nvim'
# build = 'yarn install --frozen-lockfile'
# hook_source = 'source $XDG_CONFIG_HOME/nvim/after/coc.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'
on_i = 1
hook_source = '''
  call denite#custom#map('insert', '<c-n>', '<denite:move_to_next_line>', 'noremap')
  call denite#custom#map('insert', '<c-p>', '<denite:move_to_previous_line>', 'noremap')
'''

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_source = 'denite.nvim'
on_event = 'TextYankPost'

if = 'has("nvim") && has("python3")'
[[plugins]]
repo = 'tbodt/deoplete-tabnine'
on_event = ['InsertEnter']
build = './install.sh'
on_ft = ['ruby', 'go', 'python', 'typescript', 'javascript']
