[[plugins]]
repo = 'Shougo/dein.vim'

repo = 'itchyny/lightline.vim'
hook_add = '''
  let g:lightline = {'colorscheme': 'wombat'}
'''

# auto close
[[plugins]]
repo = 'Townk/vim-autoclose'

# Toml
[[plugins]]
repo  = 'cespare/vim-toml'

# Colors
[[plugins]]
repo = 'altercation/vim-colors-solarized'

# vim-git
[[plugins]]
repo = 'tpope/vim-fugitive'

# Golang
[[plugins]]
repo = 'fatih/vim-go'

# Ruby
[[plugins]]
repo = 'vim-ruby/vim-ruby'

[[plugins]]
repo = 'tpope/vim-rails'

[[plugins]]
repo = 'thinca/vim-quickrun'

# cpp
[[plugins]]
repo = 'vim-jp/cpp-vim'

# TypeScript
[[plugins]]
repo = 'peitalin/vim-jsx-typescript'

[[plugins]]
repo = 'leafgarland/typescript-vim'
