[[plugins]]
repo = 'Shougo/dein.vim'

repo = 'itchyny/lightline.vim'
hook_add = '''
  let g:lightline = {'colorscheme': 'material'}
'''

# auto close
[[plugins]]
repo = 'Townk/vim-autoclose'

# Toml
[[plugins]]
repo  = 'cespare/vim-toml'

# Colors
[[plugins]]
repo = 'altercation/vim-colors-solarized'

# vim-git
[[plugins]]
repo = 'tpope/vim-fugitive'

# execute file on nvim
[[plugins]]
repo = 'thinca/vim-quickrun'

# cpp
[[plugins]]
repo = 'vim-jp/cpp-vim'
on_ft = ['cpp']

[[plugins]]
repo = 'osyo-manga/vim-anzu'
hook_add = '''
  nmap n <Plug>(anzu-n-with-echo)
  nmap N <Plug>(anzu-N-with-echo)
  nmap * <Plug>(anzu-star)
  nmap # <Plug>(anzu-sharp)
'''

# check syntax
[[plugins]]
repo = 'dense-analysis/ale'
hook_add = '''
  let g:ale_linters_explicit = 1
'''

