[[plugins]]
repo = 'Shougo/dein.vim'

repo = 'itchyny/lightline.vim'
hook_add = '''
  let g:lightline = {'colorscheme': 'material'}
'''

# auto close
[[plugins]]
repo = 'Townk/vim-autoclose'

[[plugins]]
repo = 'tpope/vim-endwise'

# Toml
[[plugins]]
repo = 'cespare/vim-toml'

# Colors
[[plugins]]
repo = 'jdkanani/vim-material-theme'
[[plugins]]
repo = 'tomasr/molokai'
[[plugins]]
repo = 'jacoborus/tender.vim'

# vim-git
[[plugins]]
repo = 'tpope/vim-fugitive'

# change quote
[[plugins]]
repo = 'tpope/vim-surround'
hook_add = '''
  " replace double with single.
  nmap ff <Plug>Csurround"'
  " replace single with double
  nmap tt <Plug>Csurround'"
'''

# execute file on nvim
[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'osyo-manga/vim-anzu'
hook_add = '''
  nmap n <Plug>(anzu-n-with-echo)
  nmap N <Plug>(anzu-N-with-echo)
  nmap * <Plug>(anzu-star)
  nmap # <Plug>(anzu-sharp)
'''

# check syntax
[[plugins]]
repo = 'dense-analysis/ale'
hook_add = '''
  let g:ale_linters_explicit = 1
'''
