version: 2.1
default: &default
  working_directory: ~/repo
executors:
  xenials:
    <<: *default
    docker:
      - image: linuxbrew/linuxbrew:latest
        environment:
          LANG: en_US.UTF-8
          LC_ALL: en_US.UTF-8
          LANGUAGE: en_US:en
jobs:
  build:
    executor: xenials
    steps:
      - run:
          name: prepare
          command: sudo apt-get update && sudo apt-get install -y curl git bison
      - run:
          name: install dotfiles
          command: sh -c "$(curl -fsSL https://raw.githubusercontent.com/paveg/dotfiles/master/etc/installer_darwin)"
workflows:
  version: 2
  test:
    jobs:
      - build
